# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gridder.ui'
#
# Created: Thu Apr 18 10:02:35 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Gridder(object):
    def setupUi(self, Gridder):
        Gridder.setObjectName(_fromUtf8("Gridder"))
        Gridder.resize(588, 650)
        self.gridLayout = QtGui.QGridLayout(Gridder)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolBox = QtGui.QToolBox(Gridder)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_grid = QtGui.QWidget()
        self.page_grid.setGeometry(QtCore.QRect(0, 0, 564, 490))
        self.page_grid.setObjectName(_fromUtf8("page_grid"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_grid)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.page_grid)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.listSourceLayer = QtGui.QComboBox(self.groupBox)
        self.listSourceLayer.setObjectName(_fromUtf8("listSourceLayer"))
        self.gridLayout_4.addWidget(self.listSourceLayer, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.buttonUpdateFromLayer = QtGui.QPushButton(self.groupBox)
        self.buttonUpdateFromLayer.setObjectName(_fromUtf8("buttonUpdateFromLayer"))
        self.gridLayout_3.addWidget(self.buttonUpdateFromLayer, 0, 0, 1, 1)
        self.buttonUpdateFromCanvas = QtGui.QPushButton(self.groupBox)
        self.buttonUpdateFromCanvas.setObjectName(_fromUtf8("buttonUpdateFromCanvas"))
        self.gridLayout_3.addWidget(self.buttonUpdateFromCanvas, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.textXmin = QtGui.QLineEdit(self.groupBox)
        self.textXmin.setObjectName(_fromUtf8("textXmin"))
        self.gridLayout_2.addWidget(self.textXmin, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.textYmin = QtGui.QLineEdit(self.groupBox)
        self.textYmin.setObjectName(_fromUtf8("textYmin"))
        self.gridLayout_2.addWidget(self.textYmin, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.textYmax = QtGui.QLineEdit(self.groupBox)
        self.textYmax.setObjectName(_fromUtf8("textYmax"))
        self.gridLayout_2.addWidget(self.textYmax, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_1 = QtGui.QLabel(self.groupBox)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout_2.addWidget(self.label_1, 1, 0, 1, 1)
        self.textXmax = QtGui.QLineEdit(self.groupBox)
        self.textXmax.setObjectName(_fromUtf8("textXmax"))
        self.gridLayout_2.addWidget(self.textXmax, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.page_grid)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sboxYres = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.sboxYres.setEnabled(True)
        self.sboxYres.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxYres.setMaximum(1000000000.0)
        self.sboxYres.setObjectName(_fromUtf8("sboxYres"))
        self.gridLayout_5.addWidget(self.sboxYres, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 1)
        self.sboxXres = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.sboxXres.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres.setMaximum(1000000000.0)
        self.sboxXres.setObjectName(_fromUtf8("sboxXres"))
        self.gridLayout_5.addWidget(self.sboxXres, 0, 2, 1, 1)
        self.checkRatio = QtGui.QCheckBox(self.groupBox_2)
        self.checkRatio.setObjectName(_fromUtf8("checkRatio"))
        self.gridLayout_5.addWidget(self.checkRatio, 0, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.page_grid)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.textOutFilename = QtGui.QLineEdit(self.groupBox_3)
        self.textOutFilename.setObjectName(_fromUtf8("textOutFilename"))
        self.gridLayout_7.addWidget(self.textOutFilename, 3, 1, 1, 1)
        self.buttonBrowse = QtGui.QPushButton(self.groupBox_3)
        self.buttonBrowse.setObjectName(_fromUtf8("buttonBrowse"))
        self.gridLayout_7.addWidget(self.buttonBrowse, 3, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 3, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.checkLoadLayer = QtGui.QCheckBox(self.groupBox_3)
        self.checkLoadLayer.setObjectName(_fromUtf8("checkLoadLayer"))
        self.gridLayout_8.addWidget(self.checkLoadLayer, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.progressBarBuildGrid = QtGui.QProgressBar(self.page_grid)
        self.progressBarBuildGrid.setProperty("value", 0)
        self.progressBarBuildGrid.setObjectName(_fromUtf8("progressBarBuildGrid"))
        self.horizontalLayout_3.addWidget(self.progressBarBuildGrid)
        spacerItem = QtGui.QSpacerItem(78, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonWriteGrid = QtGui.QPushButton(self.page_grid)
        self.buttonWriteGrid.setObjectName(_fromUtf8("buttonWriteGrid"))
        self.horizontalLayout_3.addWidget(self.buttonWriteGrid)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.toolBox.addItem(self.page_grid, _fromUtf8(""))
        self.page_toplogy = QtGui.QWidget()
        self.page_toplogy.setGeometry(QtCore.QRect(0, 0, 564, 490))
        self.page_toplogy.setObjectName(_fromUtf8("page_toplogy"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_toplogy)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_8 = QtGui.QLabel(self.page_toplogy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.listGridLayer = QtGui.QComboBox(self.page_toplogy)
        self.listGridLayer.setObjectName(_fromUtf8("listGridLayer"))
        self.verticalLayout_2.addWidget(self.listGridLayer)
        self.label_9 = QtGui.QLabel(self.page_toplogy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_10 = QtGui.QLabel(self.page_toplogy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.sboxDivideVert = QtGui.QSpinBox(self.page_toplogy)
        self.sboxDivideVert.setMinimum(1)
        self.sboxDivideVert.setMaximum(100)
        self.sboxDivideVert.setObjectName(_fromUtf8("sboxDivideVert"))
        self.horizontalLayout.addWidget(self.sboxDivideVert)
        self.label_11 = QtGui.QLabel(self.page_toplogy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.sboxDivideHoriz = QtGui.QSpinBox(self.page_toplogy)
        self.sboxDivideHoriz.setMinimum(1)
        self.sboxDivideHoriz.setMaximum(100)
        self.sboxDivideHoriz.setObjectName(_fromUtf8("sboxDivideHoriz"))
        self.horizontalLayout.addWidget(self.sboxDivideHoriz)
        self.checkDivideRatio = QtGui.QCheckBox(self.page_toplogy)
        self.checkDivideRatio.setObjectName(_fromUtf8("checkDivideRatio"))
        self.horizontalLayout.addWidget(self.checkDivideRatio)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.checkTopo = QtGui.QCheckBox(self.page_toplogy)
        self.checkTopo.setObjectName(_fromUtf8("checkTopo"))
        self.horizontalLayout_8.addWidget(self.checkTopo)
        self.listModelName = QtGui.QComboBox(self.page_toplogy)
        self.listModelName.setEditable(False)
        self.listModelName.setObjectName(_fromUtf8("listModelName"))
        self.horizontalLayout_8.addWidget(self.listModelName)
        spacerItem1 = QtGui.QSpacerItem(128, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.progressBarRegularRefine = QtGui.QProgressBar(self.page_toplogy)
        self.progressBarRegularRefine.setProperty("value", 0)
        self.progressBarRegularRefine.setObjectName(_fromUtf8("progressBarRegularRefine"))
        self.horizontalLayout_2.addWidget(self.progressBarRegularRefine)
        self.labelIterations = QtGui.QLabel(self.page_toplogy)
        self.labelIterations.setObjectName(_fromUtf8("labelIterations"))
        self.horizontalLayout_2.addWidget(self.labelIterations)
        self.labelIter = QtGui.QLabel(self.page_toplogy)
        self.labelIter.setObjectName(_fromUtf8("labelIter"))
        self.horizontalLayout_2.addWidget(self.labelIter)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonRegularRefile = QtGui.QPushButton(self.page_toplogy)
        self.buttonRegularRefile.setObjectName(_fromUtf8("buttonRegularRefile"))
        self.horizontalLayout_2.addWidget(self.buttonRegularRefile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 290, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.toolBox.addItem(self.page_toplogy, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 564, 490))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_12 = QtGui.QLabel(self.page)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_4.addWidget(self.label_12)
        self.listGridLayer_2 = QtGui.QComboBox(self.page)
        self.listGridLayer_2.setObjectName(_fromUtf8("listGridLayer_2"))
        self.verticalLayout_4.addWidget(self.listGridLayer_2)
        self.label_14 = QtGui.QLabel(self.page)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_4.addWidget(self.label_14)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_17 = QtGui.QLabel(self.page)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_4.addWidget(self.label_17)
        self.label_15 = QtGui.QLabel(self.page)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_4.addWidget(self.label_15)
        self.sboxXres_2 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_2.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_2.setMaximum(1000000000.0)
        self.sboxXres_2.setObjectName(_fromUtf8("sboxXres_2"))
        self.horizontalLayout_4.addWidget(self.sboxXres_2)
        self.label_16 = QtGui.QLabel(self.page)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_4.addWidget(self.label_16)
        self.sboxXres_3 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_3.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_3.setMaximum(1000000000.0)
        self.sboxXres_3.setObjectName(_fromUtf8("sboxXres_3"))
        self.horizontalLayout_4.addWidget(self.sboxXres_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_18 = QtGui.QLabel(self.page)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_6.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.page)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_6.addWidget(self.label_19)
        self.sboxXres_4 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_4.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_4.setMaximum(1000000000.0)
        self.sboxXres_4.setObjectName(_fromUtf8("sboxXres_4"))
        self.horizontalLayout_6.addWidget(self.sboxXres_4)
        self.label_20 = QtGui.QLabel(self.page)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.sboxXres_5 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_5.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_5.setMaximum(1000000000.0)
        self.sboxXres_5.setObjectName(_fromUtf8("sboxXres_5"))
        self.horizontalLayout_6.addWidget(self.sboxXres_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.buttonRefineGrid_2 = QtGui.QPushButton(self.page)
        self.buttonRefineGrid_2.setObjectName(_fromUtf8("buttonRefineGrid_2"))
        self.horizontalLayout_7.addWidget(self.buttonRefineGrid_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem5 = QtGui.QSpacerItem(20, 269, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 564, 490))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_13 = QtGui.QLabel(self.page_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_5.addWidget(self.label_13)
        self.listGridLayer_3 = QtGui.QComboBox(self.page_2)
        self.listGridLayer_3.setObjectName(_fromUtf8("listGridLayer_3"))
        self.verticalLayout_5.addWidget(self.listGridLayer_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.pushButton_2 = QtGui.QPushButton(self.page_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        spacerItem7 = QtGui.QSpacerItem(20, 367, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.toolBox, 1, 0, 1, 1)

        self.retranslateUi(Gridder)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Gridder)

    def retranslateUi(self, Gridder):
        Gridder.setWindowTitle(QtGui.QApplication.translate("Gridder", "Qgridder", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Gridder", "Grid extent", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUpdateFromLayer.setText(QtGui.QApplication.translate("Gridder", "Update extents from layer", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUpdateFromCanvas.setText(QtGui.QApplication.translate("Gridder", "Update extents from canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Gridder", "Y Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Gridder", "X Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Gridder", "Y Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("Gridder", "X Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Gridder", "Fectch extents from existing layer : ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Gridder", "Grid resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Gridder", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Gridder", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkRatio.setText(QtGui.QApplication.translate("Gridder", " 1:1 ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Gridder", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBrowse.setText(QtGui.QApplication.translate("Gridder", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Gridder", "Output layer", None, QtGui.QApplication.UnicodeUTF8))
        self.checkLoadLayer.setText(QtGui.QApplication.translate("Gridder", "Load layer after creation", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonWriteGrid.setText(QtGui.QApplication.translate("Gridder", "Build grid", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_grid), QtGui.QApplication.translate("Gridder", "Build new grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Gridder", "Grid layer :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Gridder", "Divide by :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Gridder", "vertically :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Gridder", "horizontally :", None, QtGui.QApplication.UnicodeUTF8))
        self.checkDivideRatio.setText(QtGui.QApplication.translate("Gridder", "Lock 1:1 ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.checkTopo.setText(QtGui.QApplication.translate("Gridder", "Check topology  for : ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIterations.setText(QtGui.QApplication.translate("Gridder", "Iterations : ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIter.setText(QtGui.QApplication.translate("Gridder", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRegularRefile.setText(QtGui.QApplication.translate("Gridder", "Refine selection ", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_toplogy), QtGui.QApplication.translate("Gridder", "Regular refinement", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Gridder", "Grid layer :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Gridder", "Resolution :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Gridder", "Horizontally:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Gridder", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Gridder", "Right   ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Gridder", "Vertically:    ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Gridder", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Gridder", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRefineGrid_2.setText(QtGui.QApplication.translate("Gridder", "Refine selected ", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("Gridder", "Gradual refinement", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Gridder", "Grid layer :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Gridder", "Update grid numbering", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("Gridder", "Numbering", None, QtGui.QApplication.UnicodeUTF8))

