# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qgridder_new.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QGridderNew(object):
    def setupUi(self, QGridderNew):
        QGridderNew.setObjectName("QGridderNew")
        QGridderNew.resize(546, 511)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(QGridderNew)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(QGridderNew)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.buttonUpdateFromLayer = QtWidgets.QPushButton(self.groupBox)
        self.buttonUpdateFromLayer.setObjectName("buttonUpdateFromLayer")
        self.gridLayout_3.addWidget(self.buttonUpdateFromLayer, 0, 0, 1, 1)
        self.buttonUpdateFromCanvas = QtWidgets.QPushButton(self.groupBox)
        self.buttonUpdateFromCanvas.setObjectName("buttonUpdateFromCanvas")
        self.gridLayout_3.addWidget(self.buttonUpdateFromCanvas, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.listSourceLayer = QtWidgets.QComboBox(self.groupBox)
        self.listSourceLayer.setObjectName("listSourceLayer")
        self.gridLayout_4.addWidget(self.listSourceLayer, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textXmin = QtWidgets.QLineEdit(self.groupBox)
        self.textXmin.setObjectName("textXmin")
        self.gridLayout_2.addWidget(self.textXmin, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.textYmin = QtWidgets.QLineEdit(self.groupBox)
        self.textYmin.setObjectName("textYmin")
        self.gridLayout_2.addWidget(self.textYmin, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.textYmax = QtWidgets.QLineEdit(self.groupBox)
        self.textYmax.setObjectName("textYmax")
        self.gridLayout_2.addWidget(self.textYmax, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setObjectName("label_1")
        self.gridLayout_2.addWidget(self.label_1, 1, 0, 1, 1)
        self.textXmax = QtWidgets.QLineEdit(self.groupBox)
        self.textXmax.setObjectName("textXmax")
        self.gridLayout_2.addWidget(self.textXmax, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 4, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(QGridderNew)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sboxYres = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.sboxYres.setEnabled(True)
        self.sboxYres.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxYres.setMaximum(1000000000.0)
        self.sboxYres.setObjectName("sboxYres")
        self.gridLayout_5.addWidget(self.sboxYres, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 1)
        self.sboxXres = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.sboxXres.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres.setMaximum(1000000000.0)
        self.sboxXres.setObjectName("sboxXres")
        self.gridLayout_5.addWidget(self.sboxXres, 0, 2, 1, 1)
        self.checkRatio = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkRatio.setObjectName("checkRatio")
        self.gridLayout_5.addWidget(self.checkRatio, 0, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.labelNumberCells = QtWidgets.QLabel(self.groupBox_2)
        self.labelNumberCells.setText("")
        self.labelNumberCells.setObjectName("labelNumberCells")
        self.horizontalLayout_9.addWidget(self.labelNumberCells)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(QGridderNew)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkLoadLayer = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkLoadLayer.setObjectName("checkLoadLayer")
        self.gridLayout_8.addWidget(self.checkLoadLayer, 2, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textOutFilename = QtWidgets.QLineEdit(self.groupBox_3)
        self.textOutFilename.setObjectName("textOutFilename")
        self.gridLayout_7.addWidget(self.textOutFilename, 3, 1, 1, 1)
        self.buttonBrowse = QtWidgets.QPushButton(self.groupBox_3)
        self.buttonBrowse.setObjectName("buttonBrowse")
        self.gridLayout_7.addWidget(self.buttonBrowse, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 3, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBarBuildGrid = QtWidgets.QProgressBar(QGridderNew)
        self.progressBarBuildGrid.setProperty("value", 0)
        self.progressBarBuildGrid.setObjectName("progressBarBuildGrid")
        self.horizontalLayout_3.addWidget(self.progressBarBuildGrid)
        self.labelIter = QtWidgets.QLabel(QGridderNew)
        self.labelIter.setObjectName("labelIter")
        self.horizontalLayout_3.addWidget(self.labelIter)
        spacerItem = QtWidgets.QSpacerItem(78, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonWriteGrid = QtWidgets.QPushButton(QGridderNew)
        self.buttonWriteGrid.setObjectName("buttonWriteGrid")
        self.horizontalLayout_3.addWidget(self.buttonWriteGrid)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)

        self.retranslateUi(QGridderNew)
        QtCore.QMetaObject.connectSlotsByName(QGridderNew)
        QGridderNew.setTabOrder(self.listSourceLayer, self.buttonUpdateFromLayer)
        QGridderNew.setTabOrder(self.buttonUpdateFromLayer, self.buttonUpdateFromCanvas)
        QGridderNew.setTabOrder(self.buttonUpdateFromCanvas, self.textXmin)
        QGridderNew.setTabOrder(self.textXmin, self.textYmin)
        QGridderNew.setTabOrder(self.textYmin, self.textXmax)
        QGridderNew.setTabOrder(self.textXmax, self.textYmax)
        QGridderNew.setTabOrder(self.textYmax, self.sboxXres)
        QGridderNew.setTabOrder(self.sboxXres, self.sboxYres)
        QGridderNew.setTabOrder(self.sboxYres, self.checkRatio)
        QGridderNew.setTabOrder(self.checkRatio, self.textOutFilename)
        QGridderNew.setTabOrder(self.textOutFilename, self.buttonBrowse)
        QGridderNew.setTabOrder(self.buttonBrowse, self.checkLoadLayer)
        QGridderNew.setTabOrder(self.checkLoadLayer, self.buttonWriteGrid)

    def retranslateUi(self, QGridderNew):
        _translate = QtCore.QCoreApplication.translate
        QGridderNew.setWindowTitle(_translate("QGridderNew", "Qgridder"))
        self.groupBox.setTitle(_translate("QGridderNew", "Grid extent"))
        self.buttonUpdateFromLayer.setText(_translate("QGridderNew", "Update extents from layer"))
        self.buttonUpdateFromCanvas.setText(_translate("QGridderNew", "Update extents from canvas"))
        self.textXmin.setText(_translate("QGridderNew", "0"))
        self.label_2.setText(_translate("QGridderNew", "Y Min"))
        self.textYmin.setText(_translate("QGridderNew", "0"))
        self.label_3.setText(_translate("QGridderNew", "X Min"))
        self.textYmax.setText(_translate("QGridderNew", "100"))
        self.label_4.setText(_translate("QGridderNew", "Y Max"))
        self.label_1.setText(_translate("QGridderNew", "X Max"))
        self.textXmax.setText(_translate("QGridderNew", "100"))
        self.label_7.setText(_translate("QGridderNew", "Fectch extents from existing layer : "))
        self.label_8.setText(_translate("QGridderNew", "Note : maximum values of X and Y will be adjusted to obtain exact resolution."))
        self.groupBox_2.setTitle(_translate("QGridderNew", "Grid resolution (in map unit)"))
        self.label_6.setText(_translate("QGridderNew", "Y"))
        self.label_5.setText(_translate("QGridderNew", "X"))
        self.checkRatio.setText(_translate("QGridderNew", " 1:1 ratio"))
        self.label_13.setText(_translate("QGridderNew", "Estimated number of grid cells : "))
        self.groupBox_3.setTitle(_translate("QGridderNew", "Output"))
        self.checkLoadLayer.setText(_translate("QGridderNew", "Load layer after creation"))
        self.textOutFilename.setText(_translate("QGridderNew", "grid.shp"))
        self.buttonBrowse.setText(_translate("QGridderNew", "Browse..."))
        self.label.setText(_translate("QGridderNew", "Output layer"))
        self.labelIter.setText(_translate("QGridderNew", "labelIter"))
        self.buttonWriteGrid.setText(_translate("QGridderNew", "Build grid"))

