# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qgridder.ui'
#
# Created: Fri Jan 30 10:02:13 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QGridder(object):
    def setupUi(self, QGridder):
        QGridder.setObjectName(_fromUtf8("QGridder"))
        QGridder.resize(580, 729)
        self.verticalLayout_7 = QtGui.QVBoxLayout(QGridder)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_4 = QtGui.QGroupBox(QGridder)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_12.addWidget(self.label_22)
        self.listModelName = QtGui.QComboBox(self.groupBox_4)
        self.listModelName.setEditable(False)
        self.listModelName.setObjectName(_fromUtf8("listModelName"))
        self.horizontalLayout_12.addWidget(self.listModelName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.toolBox = QtGui.QToolBox(QGridder)
        self.toolBox.setEnabled(True)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_grid = QtGui.QWidget()
        self.page_grid.setGeometry(QtCore.QRect(0, 0, 546, 501))
        self.page_grid.setObjectName(_fromUtf8("page_grid"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_grid)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.page_grid)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.buttonUpdateFromLayer = QtGui.QPushButton(self.groupBox)
        self.buttonUpdateFromLayer.setObjectName(_fromUtf8("buttonUpdateFromLayer"))
        self.gridLayout_3.addWidget(self.buttonUpdateFromLayer, 0, 0, 1, 1)
        self.buttonUpdateFromCanvas = QtGui.QPushButton(self.groupBox)
        self.buttonUpdateFromCanvas.setObjectName(_fromUtf8("buttonUpdateFromCanvas"))
        self.gridLayout_3.addWidget(self.buttonUpdateFromCanvas, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.listSourceLayer = QtGui.QComboBox(self.groupBox)
        self.listSourceLayer.setObjectName(_fromUtf8("listSourceLayer"))
        self.gridLayout_4.addWidget(self.listSourceLayer, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.textXmin = QtGui.QLineEdit(self.groupBox)
        self.textXmin.setObjectName(_fromUtf8("textXmin"))
        self.gridLayout_2.addWidget(self.textXmin, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.textYmin = QtGui.QLineEdit(self.groupBox)
        self.textYmin.setObjectName(_fromUtf8("textYmin"))
        self.gridLayout_2.addWidget(self.textYmin, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.textYmax = QtGui.QLineEdit(self.groupBox)
        self.textYmax.setObjectName(_fromUtf8("textYmax"))
        self.gridLayout_2.addWidget(self.textYmax, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_1 = QtGui.QLabel(self.groupBox)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout_2.addWidget(self.label_1, 1, 0, 1, 1)
        self.textXmax = QtGui.QLineEdit(self.groupBox)
        self.textXmax.setObjectName(_fromUtf8("textXmax"))
        self.gridLayout_2.addWidget(self.textXmax, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.page_grid)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sboxYres = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.sboxYres.setEnabled(True)
        self.sboxYres.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxYres.setMaximum(1000000000.0)
        self.sboxYres.setObjectName(_fromUtf8("sboxYres"))
        self.gridLayout_5.addWidget(self.sboxYres, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 1)
        self.sboxXres = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.sboxXres.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres.setMaximum(1000000000.0)
        self.sboxXres.setObjectName(_fromUtf8("sboxXres"))
        self.gridLayout_5.addWidget(self.sboxXres, 0, 2, 1, 1)
        self.checkRatio = QtGui.QCheckBox(self.groupBox_2)
        self.checkRatio.setObjectName(_fromUtf8("checkRatio"))
        self.gridLayout_5.addWidget(self.checkRatio, 0, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.labelNumberCells = QtGui.QLabel(self.groupBox_2)
        self.labelNumberCells.setText(_fromUtf8(""))
        self.labelNumberCells.setObjectName(_fromUtf8("labelNumberCells"))
        self.horizontalLayout_9.addWidget(self.labelNumberCells)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.page_grid)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.textOutFilename = QtGui.QLineEdit(self.groupBox_3)
        self.textOutFilename.setObjectName(_fromUtf8("textOutFilename"))
        self.gridLayout_7.addWidget(self.textOutFilename, 3, 1, 1, 1)
        self.buttonBrowse = QtGui.QPushButton(self.groupBox_3)
        self.buttonBrowse.setObjectName(_fromUtf8("buttonBrowse"))
        self.gridLayout_7.addWidget(self.buttonBrowse, 3, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 3, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.checkLoadLayer = QtGui.QCheckBox(self.groupBox_3)
        self.checkLoadLayer.setObjectName(_fromUtf8("checkLoadLayer"))
        self.gridLayout_8.addWidget(self.checkLoadLayer, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.progressBarBuildGrid = QtGui.QProgressBar(self.page_grid)
        self.progressBarBuildGrid.setProperty("value", 0)
        self.progressBarBuildGrid.setObjectName(_fromUtf8("progressBarBuildGrid"))
        self.horizontalLayout_3.addWidget(self.progressBarBuildGrid)
        spacerItem = QtGui.QSpacerItem(78, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonWriteGrid = QtGui.QPushButton(self.page_grid)
        self.buttonWriteGrid.setObjectName(_fromUtf8("buttonWriteGrid"))
        self.horizontalLayout_3.addWidget(self.buttonWriteGrid)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.toolBox.addItem(self.page_grid, _fromUtf8(""))
        self.page_toplogy = QtGui.QWidget()
        self.page_toplogy.setGeometry(QtCore.QRect(0, 0, 556, 429))
        self.page_toplogy.setObjectName(_fromUtf8("page_toplogy"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_toplogy)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.labelGridLayer = QtGui.QLabel(self.page_toplogy)
        self.labelGridLayer.setObjectName(_fromUtf8("labelGridLayer"))
        self.horizontalLayout_11.addWidget(self.labelGridLayer)
        self.listGridLayer = QtGui.QComboBox(self.page_toplogy)
        self.listGridLayer.setEnabled(True)
        self.listGridLayer.setObjectName(_fromUtf8("listGridLayer"))
        self.horizontalLayout_11.addWidget(self.listGridLayer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.label_9 = QtGui.QLabel(self.page_toplogy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_11 = QtGui.QLabel(self.page_toplogy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.sboxDivideHoriz = QtGui.QSpinBox(self.page_toplogy)
        self.sboxDivideHoriz.setMinimum(1)
        self.sboxDivideHoriz.setMaximum(100)
        self.sboxDivideHoriz.setObjectName(_fromUtf8("sboxDivideHoriz"))
        self.horizontalLayout.addWidget(self.sboxDivideHoriz)
        self.label_10 = QtGui.QLabel(self.page_toplogy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.sboxDivideVert = QtGui.QSpinBox(self.page_toplogy)
        self.sboxDivideVert.setMinimum(1)
        self.sboxDivideVert.setMaximum(100)
        self.sboxDivideVert.setObjectName(_fromUtf8("sboxDivideVert"))
        self.horizontalLayout.addWidget(self.sboxDivideVert)
        self.checkDivideRatio = QtGui.QCheckBox(self.page_toplogy)
        self.checkDivideRatio.setObjectName(_fromUtf8("checkDivideRatio"))
        self.horizontalLayout.addWidget(self.checkDivideRatio)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.checkTopo = QtGui.QCheckBox(self.page_toplogy)
        self.checkTopo.setObjectName(_fromUtf8("checkTopo"))
        self.horizontalLayout_8.addWidget(self.checkTopo)
        spacerItem1 = QtGui.QSpacerItem(128, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.progressBarRegularRefine = QtGui.QProgressBar(self.page_toplogy)
        self.progressBarRegularRefine.setProperty("value", 0)
        self.progressBarRegularRefine.setObjectName(_fromUtf8("progressBarRegularRefine"))
        self.horizontalLayout_2.addWidget(self.progressBarRegularRefine)
        self.labelIterations = QtGui.QLabel(self.page_toplogy)
        self.labelIterations.setObjectName(_fromUtf8("labelIterations"))
        self.horizontalLayout_2.addWidget(self.labelIterations)
        self.labelIter = QtGui.QLabel(self.page_toplogy)
        self.labelIter.setObjectName(_fromUtf8("labelIter"))
        self.horizontalLayout_2.addWidget(self.labelIter)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonRegularRefile = QtGui.QPushButton(self.page_toplogy)
        self.buttonRegularRefile.setObjectName(_fromUtf8("buttonRegularRefile"))
        self.horizontalLayout_2.addWidget(self.buttonRegularRefile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 290, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.toolBox.addItem(self.page_toplogy, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 556, 429))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_12 = QtGui.QLabel(self.page)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_4.addWidget(self.label_12)
        self.listGridLayer_2 = QtGui.QComboBox(self.page)
        self.listGridLayer_2.setObjectName(_fromUtf8("listGridLayer_2"))
        self.verticalLayout_4.addWidget(self.listGridLayer_2)
        self.label_14 = QtGui.QLabel(self.page)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_4.addWidget(self.label_14)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_17 = QtGui.QLabel(self.page)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_4.addWidget(self.label_17)
        self.label_15 = QtGui.QLabel(self.page)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_4.addWidget(self.label_15)
        self.sboxXres_2 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_2.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_2.setMaximum(1000000000.0)
        self.sboxXres_2.setObjectName(_fromUtf8("sboxXres_2"))
        self.horizontalLayout_4.addWidget(self.sboxXres_2)
        self.label_16 = QtGui.QLabel(self.page)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_4.addWidget(self.label_16)
        self.sboxXres_3 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_3.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_3.setMaximum(1000000000.0)
        self.sboxXres_3.setObjectName(_fromUtf8("sboxXres_3"))
        self.horizontalLayout_4.addWidget(self.sboxXres_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_18 = QtGui.QLabel(self.page)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_6.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.page)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_6.addWidget(self.label_19)
        self.sboxXres_4 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_4.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_4.setMaximum(1000000000.0)
        self.sboxXres_4.setObjectName(_fromUtf8("sboxXres_4"))
        self.horizontalLayout_6.addWidget(self.sboxXres_4)
        self.label_20 = QtGui.QLabel(self.page)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.sboxXres_5 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_5.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_5.setMaximum(1000000000.0)
        self.sboxXres_5.setObjectName(_fromUtf8("sboxXres_5"))
        self.horizontalLayout_6.addWidget(self.sboxXres_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.buttonRefineGrid_2 = QtGui.QPushButton(self.page)
        self.buttonRefineGrid_2.setObjectName(_fromUtf8("buttonRefineGrid_2"))
        self.horizontalLayout_7.addWidget(self.buttonRefineGrid_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem5 = QtGui.QSpacerItem(20, 269, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 556, 429))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.frame = QtGui.QFrame(self.page_4)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_25 = QtGui.QLabel(self.frame)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_10.addWidget(self.label_25)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.listLayers3D = QtGui.QListWidget(self.frame)
        self.listLayers3D.setObjectName(_fromUtf8("listLayers3D"))
        self.horizontalLayout_10.addWidget(self.listLayers3D)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.buttonLayer3DUp = QtGui.QPushButton(self.frame)
        self.buttonLayer3DUp.setObjectName(_fromUtf8("buttonLayer3DUp"))
        self.verticalLayout_8.addWidget(self.buttonLayer3DUp)
        self.buttonLayer3DDown = QtGui.QPushButton(self.frame)
        self.buttonLayer3DDown.setObjectName(_fromUtf8("buttonLayer3DDown"))
        self.verticalLayout_8.addWidget(self.buttonLayer3DDown)
        self.buttonLayer3DRemove = QtGui.QPushButton(self.frame)
        self.buttonLayer3DRemove.setObjectName(_fromUtf8("buttonLayer3DRemove"))
        self.verticalLayout_8.addWidget(self.buttonLayer3DRemove)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.label_23 = QtGui.QLabel(self.frame)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_10.addWidget(self.label_23)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setMaximumSize(QtCore.QSize(175, 16777215))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_14.addWidget(self.label_21)
        self.listReferenceGrid = QtGui.QComboBox(self.frame)
        self.listReferenceGrid.setObjectName(_fromUtf8("listReferenceGrid"))
        self.horizontalLayout_14.addWidget(self.listReferenceGrid)
        self.buttonAddNewLayer3D = QtGui.QPushButton(self.frame)
        self.buttonAddNewLayer3D.setMaximumSize(QtCore.QSize(140, 16777215))
        self.buttonAddNewLayer3D.setObjectName(_fromUtf8("buttonAddNewLayer3D"))
        self.horizontalLayout_14.addWidget(self.buttonAddNewLayer3D)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_24 = QtGui.QLabel(self.frame)
        self.label_24.setMaximumSize(QtCore.QSize(175, 16777215))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_16.addWidget(self.label_24)
        self.listExistingLayer = QtGui.QComboBox(self.frame)
        self.listExistingLayer.setObjectName(_fromUtf8("listExistingLayer"))
        self.horizontalLayout_16.addWidget(self.listExistingLayer)
        self.buttonAddExistingLayer3D = QtGui.QPushButton(self.frame)
        self.buttonAddExistingLayer3D.setMaximumSize(QtCore.QSize(140, 16777215))
        self.buttonAddExistingLayer3D.setObjectName(_fromUtf8("buttonAddExistingLayer3D"))
        self.horizontalLayout_16.addWidget(self.buttonAddExistingLayer3D)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.verticalLayout_9.addWidget(self.frame)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.progressBarCheck3D = QtGui.QProgressBar(self.page_4)
        self.progressBarCheck3D.setProperty("value", 0)
        self.progressBarCheck3D.setObjectName(_fromUtf8("progressBarCheck3D"))
        self.horizontalLayout_15.addWidget(self.progressBarCheck3D)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.buttonCheck3D = QtGui.QPushButton(self.page_4)
        self.buttonCheck3D.setObjectName(_fromUtf8("buttonCheck3D"))
        self.horizontalLayout_15.addWidget(self.buttonCheck3D)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 556, 429))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.buttonProceedNumbering = QtGui.QPushButton(self.page_3)
        self.buttonProceedNumbering.setObjectName(_fromUtf8("buttonProceedNumbering"))
        self.horizontalLayout_13.addWidget(self.buttonProceedNumbering)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        spacerItem8 = QtGui.QSpacerItem(20, 459, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 556, 429))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.textOutTextFileName = QtGui.QLineEdit(self.page_2)
        self.textOutTextFileName.setObjectName(_fromUtf8("textOutTextFileName"))
        self.horizontalLayout_17.addWidget(self.textOutTextFileName)
        self.buttonBrowseTextFile = QtGui.QPushButton(self.page_2)
        self.buttonBrowseTextFile.setObjectName(_fromUtf8("buttonBrowseTextFile"))
        self.horizontalLayout_17.addWidget(self.buttonBrowseTextFile)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.buttonExportTextFile = QtGui.QPushButton(self.page_2)
        self.buttonExportTextFile.setObjectName(_fromUtf8("buttonExportTextFile"))
        self.horizontalLayout_5.addWidget(self.buttonExportTextFile)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        spacerItem10 = QtGui.QSpacerItem(598, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem10)
        spacerItem11 = QtGui.QSpacerItem(20, 367, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.toolBox)

        self.retranslateUi(QGridder)
        self.toolBox.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(QGridder)
        QGridder.setTabOrder(self.listModelName, self.listSourceLayer)
        QGridder.setTabOrder(self.listSourceLayer, self.buttonUpdateFromLayer)
        QGridder.setTabOrder(self.buttonUpdateFromLayer, self.buttonUpdateFromCanvas)
        QGridder.setTabOrder(self.buttonUpdateFromCanvas, self.textXmin)
        QGridder.setTabOrder(self.textXmin, self.textYmin)
        QGridder.setTabOrder(self.textYmin, self.textXmax)
        QGridder.setTabOrder(self.textXmax, self.textYmax)
        QGridder.setTabOrder(self.textYmax, self.sboxXres)
        QGridder.setTabOrder(self.sboxXres, self.sboxYres)
        QGridder.setTabOrder(self.sboxYres, self.checkRatio)
        QGridder.setTabOrder(self.checkRatio, self.textOutFilename)
        QGridder.setTabOrder(self.textOutFilename, self.buttonBrowse)
        QGridder.setTabOrder(self.buttonBrowse, self.checkLoadLayer)
        QGridder.setTabOrder(self.checkLoadLayer, self.buttonWriteGrid)
        QGridder.setTabOrder(self.buttonWriteGrid, self.sboxDivideVert)
        QGridder.setTabOrder(self.sboxDivideVert, self.checkDivideRatio)
        QGridder.setTabOrder(self.checkDivideRatio, self.checkTopo)
        QGridder.setTabOrder(self.checkTopo, self.buttonRegularRefile)
        QGridder.setTabOrder(self.buttonRegularRefile, self.listGridLayer_2)
        QGridder.setTabOrder(self.listGridLayer_2, self.sboxXres_2)
        QGridder.setTabOrder(self.sboxXres_2, self.sboxXres_3)
        QGridder.setTabOrder(self.sboxXres_3, self.sboxXres_4)
        QGridder.setTabOrder(self.sboxXres_4, self.sboxXres_5)
        QGridder.setTabOrder(self.sboxXres_5, self.buttonRefineGrid_2)
        QGridder.setTabOrder(self.buttonRefineGrid_2, self.buttonProceedNumbering)
        QGridder.setTabOrder(self.buttonProceedNumbering, self.buttonExportTextFile)

    def retranslateUi(self, QGridder):
        QGridder.setWindowTitle(_translate("QGridder", "Qgridder", None))
        self.label_22.setText(_translate("QGridder", "Model type :", None))
        self.groupBox.setTitle(_translate("QGridder", "Grid extent", None))
        self.buttonUpdateFromLayer.setText(_translate("QGridder", "Update extents from layer", None))
        self.buttonUpdateFromCanvas.setText(_translate("QGridder", "Update extents from canvas", None))
        self.textXmin.setText(_translate("QGridder", "0", None))
        self.label_2.setText(_translate("QGridder", "Y Min", None))
        self.textYmin.setText(_translate("QGridder", "0", None))
        self.label_3.setText(_translate("QGridder", "X Min", None))
        self.textYmax.setText(_translate("QGridder", "100", None))
        self.label_4.setText(_translate("QGridder", "Y Max", None))
        self.label_1.setText(_translate("QGridder", "X Max", None))
        self.textXmax.setText(_translate("QGridder", "100", None))
        self.label_7.setText(_translate("QGridder", "Fectch extents from existing layer : ", None))
        self.label_8.setText(_translate("QGridder", "Note : maximum values of X and Y will be adjusted to obtain exact resolution.", None))
        self.groupBox_2.setTitle(_translate("QGridder", "Grid resolution (in map unit)", None))
        self.label_6.setText(_translate("QGridder", "Y", None))
        self.label_5.setText(_translate("QGridder", "X", None))
        self.checkRatio.setText(_translate("QGridder", " 1:1 ratio", None))
        self.label_13.setText(_translate("QGridder", "Estimated number of grid cells : ", None))
        self.groupBox_3.setTitle(_translate("QGridder", "Output", None))
        self.textOutFilename.setText(_translate("QGridder", "grid.shp", None))
        self.buttonBrowse.setText(_translate("QGridder", "Browse...", None))
        self.label.setText(_translate("QGridder", "Output layer", None))
        self.checkLoadLayer.setText(_translate("QGridder", "Load layer after creation", None))
        self.buttonWriteGrid.setText(_translate("QGridder", "Build grid", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_grid), _translate("QGridder", "Build new grid", None))
        self.labelGridLayer.setText(_translate("QGridder", "Grid layer :", None))
        self.label_9.setText(_translate("QGridder", "Divide by :", None))
        self.label_11.setText(_translate("QGridder", "horizontally :", None))
        self.label_10.setText(_translate("QGridder", "vertically :", None))
        self.checkDivideRatio.setText(_translate("QGridder", "Lock 1:1 ratio", None))
        self.checkTopo.setText(_translate("QGridder", "Check topology  for selected model type", None))
        self.labelIterations.setText(_translate("QGridder", "Iterations : ", None))
        self.labelIter.setText(_translate("QGridder", "0", None))
        self.buttonRegularRefile.setText(_translate("QGridder", "Refine selection ", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_toplogy), _translate("QGridder", "Regular refinement", None))
        self.label_12.setText(_translate("QGridder", "Grid layer :", None))
        self.label_14.setText(_translate("QGridder", "Resolution :", None))
        self.label_17.setText(_translate("QGridder", "Horizontally:", None))
        self.label_15.setText(_translate("QGridder", "Left", None))
        self.label_16.setText(_translate("QGridder", "Right   ", None))
        self.label_18.setText(_translate("QGridder", "Vertically:    ", None))
        self.label_19.setText(_translate("QGridder", "Top", None))
        self.label_20.setText(_translate("QGridder", "Bottom", None))
        self.buttonRefineGrid_2.setText(_translate("QGridder", "Refine selection", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("QGridder", "Gradual refinement", None))
        self.label_25.setText(_translate("QGridder", "List of layers (from top to bottom) : ", None))
        self.buttonLayer3DUp.setText(_translate("QGridder", "Up", None))
        self.buttonLayer3DDown.setText(_translate("QGridder", "Down", None))
        self.buttonLayer3DRemove.setText(_translate("QGridder", "Remove", None))
        self.label_23.setText(_translate("QGridder", "Add layer to list : ", None))
        self.label_21.setText(_translate("QGridder", "New from reference grid :", None))
        self.buttonAddNewLayer3D.setText(_translate("QGridder", "Add new layer...", None))
        self.label_24.setText(_translate("QGridder", "Import existing layer : ", None))
        self.buttonAddExistingLayer3D.setText(_translate("QGridder", "Add existing layer", None))
        self.buttonCheck3D.setText(_translate("QGridder", "Check and correct 3D topology", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("QGridder", "Pseudo-3D Grid", None))
        self.buttonProceedNumbering.setText(_translate("QGridder", "Proceed to numbering", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("QGridder", "Pre-processing", None))
        self.buttonBrowseTextFile.setText(_translate("QGridder", "Browse ...", None))
        self.buttonExportTextFile.setText(_translate("QGridder", "Export", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("QGridder", "Export grid to text", None))

