# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qgridder.ui'
#
# Created: Fri May 24 12:54:37 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QGridder(object):
    def setupUi(self, QGridder):
        QGridder.setObjectName(_fromUtf8("QGridder"))
        QGridder.resize(621, 844)
        self.verticalLayout_7 = QtGui.QVBoxLayout(QGridder)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_4 = QtGui.QGroupBox(QGridder)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_12.addWidget(self.label_22)
        self.listModelName = QtGui.QComboBox(self.groupBox_4)
        self.listModelName.setEditable(False)
        self.listModelName.setObjectName(_fromUtf8("listModelName"))
        self.horizontalLayout_12.addWidget(self.listModelName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.labelGridLayer = QtGui.QLabel(self.groupBox_4)
        self.labelGridLayer.setObjectName(_fromUtf8("labelGridLayer"))
        self.horizontalLayout_11.addWidget(self.labelGridLayer)
        self.listGridLayer = QtGui.QComboBox(self.groupBox_4)
        self.listGridLayer.setEnabled(True)
        self.listGridLayer.setObjectName(_fromUtf8("listGridLayer"))
        self.horizontalLayout_11.addWidget(self.listGridLayer)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.toolBox = QtGui.QToolBox(QGridder)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_grid = QtGui.QWidget()
        self.page_grid.setGeometry(QtCore.QRect(0, 0, 597, 542))
        self.page_grid.setObjectName(_fromUtf8("page_grid"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_grid)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.page_grid)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.listSourceLayer = QtGui.QComboBox(self.groupBox)
        self.listSourceLayer.setObjectName(_fromUtf8("listSourceLayer"))
        self.gridLayout_4.addWidget(self.listSourceLayer, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.buttonUpdateFromLayer = QtGui.QPushButton(self.groupBox)
        self.buttonUpdateFromLayer.setObjectName(_fromUtf8("buttonUpdateFromLayer"))
        self.gridLayout_3.addWidget(self.buttonUpdateFromLayer, 0, 0, 1, 1)
        self.buttonUpdateFromCanvas = QtGui.QPushButton(self.groupBox)
        self.buttonUpdateFromCanvas.setObjectName(_fromUtf8("buttonUpdateFromCanvas"))
        self.gridLayout_3.addWidget(self.buttonUpdateFromCanvas, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.textXmin = QtGui.QLineEdit(self.groupBox)
        self.textXmin.setObjectName(_fromUtf8("textXmin"))
        self.gridLayout_2.addWidget(self.textXmin, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.textYmin = QtGui.QLineEdit(self.groupBox)
        self.textYmin.setObjectName(_fromUtf8("textYmin"))
        self.gridLayout_2.addWidget(self.textYmin, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.textYmax = QtGui.QLineEdit(self.groupBox)
        self.textYmax.setObjectName(_fromUtf8("textYmax"))
        self.gridLayout_2.addWidget(self.textYmax, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_1 = QtGui.QLabel(self.groupBox)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout_2.addWidget(self.label_1, 1, 0, 1, 1)
        self.textXmax = QtGui.QLineEdit(self.groupBox)
        self.textXmax.setObjectName(_fromUtf8("textXmax"))
        self.gridLayout_2.addWidget(self.textXmax, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.page_grid)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sboxYres = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.sboxYres.setEnabled(True)
        self.sboxYres.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxYres.setMaximum(1000000000.0)
        self.sboxYres.setObjectName(_fromUtf8("sboxYres"))
        self.gridLayout_5.addWidget(self.sboxYres, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 1)
        self.sboxXres = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.sboxXres.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres.setMaximum(1000000000.0)
        self.sboxXres.setObjectName(_fromUtf8("sboxXres"))
        self.gridLayout_5.addWidget(self.sboxXres, 0, 2, 1, 1)
        self.checkRatio = QtGui.QCheckBox(self.groupBox_2)
        self.checkRatio.setObjectName(_fromUtf8("checkRatio"))
        self.gridLayout_5.addWidget(self.checkRatio, 0, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.labelNumberCells = QtGui.QLabel(self.groupBox_2)
        self.labelNumberCells.setText(_fromUtf8(""))
        self.labelNumberCells.setObjectName(_fromUtf8("labelNumberCells"))
        self.horizontalLayout_9.addWidget(self.labelNumberCells)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.page_grid)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.textOutFilename = QtGui.QLineEdit(self.groupBox_3)
        self.textOutFilename.setObjectName(_fromUtf8("textOutFilename"))
        self.gridLayout_7.addWidget(self.textOutFilename, 3, 1, 1, 1)
        self.buttonBrowse = QtGui.QPushButton(self.groupBox_3)
        self.buttonBrowse.setObjectName(_fromUtf8("buttonBrowse"))
        self.gridLayout_7.addWidget(self.buttonBrowse, 3, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 3, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.checkLoadLayer = QtGui.QCheckBox(self.groupBox_3)
        self.checkLoadLayer.setObjectName(_fromUtf8("checkLoadLayer"))
        self.gridLayout_8.addWidget(self.checkLoadLayer, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.progressBarBuildGrid = QtGui.QProgressBar(self.page_grid)
        self.progressBarBuildGrid.setProperty("value", 0)
        self.progressBarBuildGrid.setObjectName(_fromUtf8("progressBarBuildGrid"))
        self.horizontalLayout_3.addWidget(self.progressBarBuildGrid)
        spacerItem = QtGui.QSpacerItem(78, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonWriteGrid = QtGui.QPushButton(self.page_grid)
        self.buttonWriteGrid.setObjectName(_fromUtf8("buttonWriteGrid"))
        self.horizontalLayout_3.addWidget(self.buttonWriteGrid)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.toolBox.addItem(self.page_grid, _fromUtf8(""))
        self.page_toplogy = QtGui.QWidget()
        self.page_toplogy.setGeometry(QtCore.QRect(0, 0, 597, 542))
        self.page_toplogy.setObjectName(_fromUtf8("page_toplogy"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_toplogy)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_9 = QtGui.QLabel(self.page_toplogy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_11 = QtGui.QLabel(self.page_toplogy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.sboxDivideHoriz = QtGui.QSpinBox(self.page_toplogy)
        self.sboxDivideHoriz.setMinimum(1)
        self.sboxDivideHoriz.setMaximum(100)
        self.sboxDivideHoriz.setObjectName(_fromUtf8("sboxDivideHoriz"))
        self.horizontalLayout.addWidget(self.sboxDivideHoriz)
        self.label_10 = QtGui.QLabel(self.page_toplogy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.sboxDivideVert = QtGui.QSpinBox(self.page_toplogy)
        self.sboxDivideVert.setMinimum(1)
        self.sboxDivideVert.setMaximum(100)
        self.sboxDivideVert.setObjectName(_fromUtf8("sboxDivideVert"))
        self.horizontalLayout.addWidget(self.sboxDivideVert)
        self.checkDivideRatio = QtGui.QCheckBox(self.page_toplogy)
        self.checkDivideRatio.setObjectName(_fromUtf8("checkDivideRatio"))
        self.horizontalLayout.addWidget(self.checkDivideRatio)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.checkTopo = QtGui.QCheckBox(self.page_toplogy)
        self.checkTopo.setObjectName(_fromUtf8("checkTopo"))
        self.horizontalLayout_8.addWidget(self.checkTopo)
        spacerItem1 = QtGui.QSpacerItem(128, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.progressBarRegularRefine = QtGui.QProgressBar(self.page_toplogy)
        self.progressBarRegularRefine.setProperty("value", 0)
        self.progressBarRegularRefine.setObjectName(_fromUtf8("progressBarRegularRefine"))
        self.horizontalLayout_2.addWidget(self.progressBarRegularRefine)
        self.labelIterations = QtGui.QLabel(self.page_toplogy)
        self.labelIterations.setObjectName(_fromUtf8("labelIterations"))
        self.horizontalLayout_2.addWidget(self.labelIterations)
        self.labelIter = QtGui.QLabel(self.page_toplogy)
        self.labelIter.setObjectName(_fromUtf8("labelIter"))
        self.horizontalLayout_2.addWidget(self.labelIter)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonRegularRefile = QtGui.QPushButton(self.page_toplogy)
        self.buttonRegularRefile.setObjectName(_fromUtf8("buttonRegularRefile"))
        self.horizontalLayout_2.addWidget(self.buttonRegularRefile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 290, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.toolBox.addItem(self.page_toplogy, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 597, 542))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_12 = QtGui.QLabel(self.page)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_4.addWidget(self.label_12)
        self.listGridLayer_2 = QtGui.QComboBox(self.page)
        self.listGridLayer_2.setObjectName(_fromUtf8("listGridLayer_2"))
        self.verticalLayout_4.addWidget(self.listGridLayer_2)
        self.label_14 = QtGui.QLabel(self.page)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_4.addWidget(self.label_14)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_17 = QtGui.QLabel(self.page)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_4.addWidget(self.label_17)
        self.label_15 = QtGui.QLabel(self.page)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_4.addWidget(self.label_15)
        self.sboxXres_2 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_2.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_2.setMaximum(1000000000.0)
        self.sboxXres_2.setObjectName(_fromUtf8("sboxXres_2"))
        self.horizontalLayout_4.addWidget(self.sboxXres_2)
        self.label_16 = QtGui.QLabel(self.page)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_4.addWidget(self.label_16)
        self.sboxXres_3 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_3.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_3.setMaximum(1000000000.0)
        self.sboxXres_3.setObjectName(_fromUtf8("sboxXres_3"))
        self.horizontalLayout_4.addWidget(self.sboxXres_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_18 = QtGui.QLabel(self.page)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_6.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.page)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_6.addWidget(self.label_19)
        self.sboxXres_4 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_4.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_4.setMaximum(1000000000.0)
        self.sboxXres_4.setObjectName(_fromUtf8("sboxXres_4"))
        self.horizontalLayout_6.addWidget(self.sboxXres_4)
        self.label_20 = QtGui.QLabel(self.page)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.sboxXres_5 = QtGui.QDoubleSpinBox(self.page)
        self.sboxXres_5.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres_5.setMaximum(1000000000.0)
        self.sboxXres_5.setObjectName(_fromUtf8("sboxXres_5"))
        self.horizontalLayout_6.addWidget(self.sboxXres_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.buttonRefineGrid_2 = QtGui.QPushButton(self.page)
        self.buttonRefineGrid_2.setObjectName(_fromUtf8("buttonRefineGrid_2"))
        self.horizontalLayout_7.addWidget(self.buttonRefineGrid_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem5 = QtGui.QSpacerItem(20, 269, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 597, 542))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.buttonProceedNumbering = QtGui.QPushButton(self.page_3)
        self.buttonProceedNumbering.setObjectName(_fromUtf8("buttonProceedNumbering"))
        self.horizontalLayout_13.addWidget(self.buttonProceedNumbering)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        spacerItem7 = QtGui.QSpacerItem(20, 459, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 597, 542))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.progressBarExport = QtGui.QProgressBar(self.page_2)
        self.progressBarExport.setProperty("value", 0)
        self.progressBarExport.setObjectName(_fromUtf8("progressBarExport"))
        self.horizontalLayout_5.addWidget(self.progressBarExport)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.buttonExport = QtGui.QPushButton(self.page_2)
        self.buttonExport.setObjectName(_fromUtf8("buttonExport"))
        self.horizontalLayout_5.addWidget(self.buttonExport)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        spacerItem9 = QtGui.QSpacerItem(598, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem9)
        spacerItem10 = QtGui.QSpacerItem(20, 367, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.toolBox)

        self.retranslateUi(QGridder)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QGridder)
        QGridder.setTabOrder(self.listModelName, self.listGridLayer)
        QGridder.setTabOrder(self.listGridLayer, self.listSourceLayer)
        QGridder.setTabOrder(self.listSourceLayer, self.buttonUpdateFromLayer)
        QGridder.setTabOrder(self.buttonUpdateFromLayer, self.buttonUpdateFromCanvas)
        QGridder.setTabOrder(self.buttonUpdateFromCanvas, self.textXmin)
        QGridder.setTabOrder(self.textXmin, self.textYmin)
        QGridder.setTabOrder(self.textYmin, self.textXmax)
        QGridder.setTabOrder(self.textXmax, self.textYmax)
        QGridder.setTabOrder(self.textYmax, self.sboxXres)
        QGridder.setTabOrder(self.sboxXres, self.sboxYres)
        QGridder.setTabOrder(self.sboxYres, self.checkRatio)
        QGridder.setTabOrder(self.checkRatio, self.textOutFilename)
        QGridder.setTabOrder(self.textOutFilename, self.buttonBrowse)
        QGridder.setTabOrder(self.buttonBrowse, self.checkLoadLayer)
        QGridder.setTabOrder(self.checkLoadLayer, self.buttonWriteGrid)
        QGridder.setTabOrder(self.buttonWriteGrid, self.sboxDivideVert)
        QGridder.setTabOrder(self.sboxDivideVert, self.checkDivideRatio)
        QGridder.setTabOrder(self.checkDivideRatio, self.checkTopo)
        QGridder.setTabOrder(self.checkTopo, self.buttonRegularRefile)
        QGridder.setTabOrder(self.buttonRegularRefile, self.listGridLayer_2)
        QGridder.setTabOrder(self.listGridLayer_2, self.sboxXres_2)
        QGridder.setTabOrder(self.sboxXres_2, self.sboxXres_3)
        QGridder.setTabOrder(self.sboxXres_3, self.sboxXres_4)
        QGridder.setTabOrder(self.sboxXres_4, self.sboxXres_5)
        QGridder.setTabOrder(self.sboxXres_5, self.buttonRefineGrid_2)
        QGridder.setTabOrder(self.buttonRefineGrid_2, self.buttonProceedNumbering)
        QGridder.setTabOrder(self.buttonProceedNumbering, self.buttonExport)

    def retranslateUi(self, QGridder):
        QGridder.setWindowTitle(QtGui.QApplication.translate("QGridder", "Qgridder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("QGridder", "Model type :", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGridLayer.setText(QtGui.QApplication.translate("QGridder", "Grid layer :", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("QGridder", "Grid extent", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUpdateFromLayer.setText(QtGui.QApplication.translate("QGridder", "Update extents from layer", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUpdateFromCanvas.setText(QtGui.QApplication.translate("QGridder", "Update extents from canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.textXmin.setText(QtGui.QApplication.translate("QGridder", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("QGridder", "Y Min", None, QtGui.QApplication.UnicodeUTF8))
        self.textYmin.setText(QtGui.QApplication.translate("QGridder", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("QGridder", "X Min", None, QtGui.QApplication.UnicodeUTF8))
        self.textYmax.setText(QtGui.QApplication.translate("QGridder", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("QGridder", "Y Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("QGridder", "X Max", None, QtGui.QApplication.UnicodeUTF8))
        self.textXmax.setText(QtGui.QApplication.translate("QGridder", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("QGridder", "Fectch extents from existing layer : ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("QGridder", "Grid resolution (in map unit)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("QGridder", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("QGridder", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkRatio.setText(QtGui.QApplication.translate("QGridder", " 1:1 ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("QGridder", "Estimated number of grid cells : ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("QGridder", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.textOutFilename.setText(QtGui.QApplication.translate("QGridder", "grid.shp", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBrowse.setText(QtGui.QApplication.translate("QGridder", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("QGridder", "Output layer", None, QtGui.QApplication.UnicodeUTF8))
        self.checkLoadLayer.setText(QtGui.QApplication.translate("QGridder", "Load layer after creation", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonWriteGrid.setText(QtGui.QApplication.translate("QGridder", "Build grid", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_grid), QtGui.QApplication.translate("QGridder", "Build new grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("QGridder", "Divide by :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("QGridder", "horizontally :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("QGridder", "vertically :", None, QtGui.QApplication.UnicodeUTF8))
        self.checkDivideRatio.setText(QtGui.QApplication.translate("QGridder", "Lock 1:1 ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.checkTopo.setText(QtGui.QApplication.translate("QGridder", "Check topology  for selected model type", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIterations.setText(QtGui.QApplication.translate("QGridder", "Iterations : ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIter.setText(QtGui.QApplication.translate("QGridder", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRegularRefile.setText(QtGui.QApplication.translate("QGridder", "Refine selection ", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_toplogy), QtGui.QApplication.translate("QGridder", "Regular refinement", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("QGridder", "Grid layer :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("QGridder", "Resolution :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("QGridder", "Horizontally:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("QGridder", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("QGridder", "Right   ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("QGridder", "Vertically:    ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("QGridder", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("QGridder", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRefineGrid_2.setText(QtGui.QApplication.translate("QGridder", "Refine selection", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("QGridder", "Gradual refinement", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonProceedNumbering.setText(QtGui.QApplication.translate("QGridder", "Proceed to numbering", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("QGridder", "Pre-processing", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonExport.setText(QtGui.QApplication.translate("QGridder", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("QGridder", "Export", None, QtGui.QApplication.UnicodeUTF8))

