# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qgridder_settings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QGridderSettings(object):
    def setupUi(self, QGridderSettings):
        QGridderSettings.setObjectName("QGridderSettings")
        QGridderSettings.resize(541, 727)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(QGridderSettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(QGridderSettings)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_12.addWidget(self.label_22)
        self.listModelTypes = QtWidgets.QComboBox(self.groupBox_4)
        self.listModelTypes.setEditable(False)
        self.listModelTypes.setObjectName("listModelTypes")
        self.horizontalLayout_12.addWidget(self.listModelTypes)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkGridBackup = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkGridBackup.setChecked(False)
        self.checkGridBackup.setObjectName("checkGridBackup")
        self.horizontalLayout_5.addWidget(self.checkGridBackup)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(QGridderSettings)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkPlotSimul = QtWidgets.QCheckBox(self.groupBox)
        self.checkPlotSimul.setChecked(True)
        self.checkPlotSimul.setObjectName("checkPlotSimul")
        self.gridLayout.addWidget(self.checkPlotSimul, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textObsDir = QtWidgets.QLineEdit(self.groupBox)
        self.textObsDir.setReadOnly(False)
        self.textObsDir.setObjectName("textObsDir")
        self.horizontalLayout.addWidget(self.textObsDir)
        self.buttonBrowseObsDir = QtWidgets.QPushButton(self.groupBox)
        self.buttonBrowseObsDir.setObjectName("buttonBrowseObsDir")
        self.horizontalLayout.addWidget(self.buttonBrowseObsDir)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.checkPlotObs = QtWidgets.QCheckBox(self.groupBox)
        self.checkPlotObs.setChecked(True)
        self.checkPlotObs.setObjectName("checkPlotObs")
        self.gridLayout.addWidget(self.checkPlotObs, 0, 0, 1, 1)
        self.labelSimulSources = QtWidgets.QLabel(self.groupBox)
        self.labelSimulSources.setObjectName("labelSimulSources")
        self.gridLayout.addWidget(self.labelSimulSources, 5, 0, 1, 1)
        self.groupBoxSimulFlopy = QtWidgets.QGroupBox(self.groupBox)
        self.groupBoxSimulFlopy.setEnabled(True)
        self.groupBoxSimulFlopy.setObjectName("groupBoxSimulFlopy")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxSimulFlopy)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labe = QtWidgets.QLabel(self.groupBoxSimulFlopy)
        self.labe.setObjectName("labe")
        self.horizontalLayout_4.addWidget(self.labe)
        self.textModelDir = QtWidgets.QLineEdit(self.groupBoxSimulFlopy)
        self.textModelDir.setReadOnly(False)
        self.textModelDir.setObjectName("textModelDir")
        self.horizontalLayout_4.addWidget(self.textModelDir)
        self.buttonBrowseModelSrcDir = QtWidgets.QPushButton(self.groupBoxSimulFlopy)
        self.buttonBrowseModelSrcDir.setObjectName("buttonBrowseModelSrcDir")
        self.horizontalLayout_4.addWidget(self.buttonBrowseModelSrcDir)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labe_3 = QtWidgets.QLabel(self.groupBoxSimulFlopy)
        self.labe_3.setObjectName("labe_3")
        self.horizontalLayout_3.addWidget(self.labe_3)
        self.textSimulFile = QtWidgets.QLineEdit(self.groupBoxSimulFlopy)
        self.textSimulFile.setReadOnly(False)
        self.textSimulFile.setObjectName("textSimulFile")
        self.horizontalLayout_3.addWidget(self.textSimulFile)
        self.buttonBrowseSimulFile = QtWidgets.QPushButton(self.groupBoxSimulFlopy)
        self.buttonBrowseSimulFile.setObjectName("buttonBrowseSimulFile")
        self.horizontalLayout_3.addWidget(self.buttonBrowseSimulFile)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBoxSimulFlopy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.textSimulStartDate = QtWidgets.QLineEdit(self.groupBoxSimulFlopy)
        self.textSimulStartDate.setObjectName("textSimulStartDate")
        self.horizontalLayout_6.addWidget(self.textSimulStartDate)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelGridLayer = QtWidgets.QLabel(self.groupBoxSimulFlopy)
        self.labelGridLayer.setObjectName("labelGridLayer")
        self.horizontalLayout_7.addWidget(self.labelGridLayer)
        self.listGridLayer = QtWidgets.QComboBox(self.groupBoxSimulFlopy)
        self.listGridLayer.setEnabled(True)
        self.listGridLayer.setObjectName("listGridLayer")
        self.horizontalLayout_7.addWidget(self.listGridLayer)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addWidget(self.groupBoxSimulFlopy, 13, 0, 1, 1)
        self.labe_2 = QtWidgets.QLabel(self.groupBox)
        self.labe_2.setObjectName("labe_2")
        self.gridLayout.addWidget(self.labe_2, 1, 0, 1, 1)
        self.listSimulSources = QtWidgets.QComboBox(self.groupBox)
        self.listSimulSources.setObjectName("listSimulSources")
        self.gridLayout.addWidget(self.listSimulSources, 6, 0, 1, 1)
        self.groupBoxSimulText = QtWidgets.QGroupBox(self.groupBox)
        self.groupBoxSimulText.setEnabled(True)
        self.groupBoxSimulText.setObjectName("groupBoxSimulText")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxSimulText)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.textSimulDir = QtWidgets.QLineEdit(self.groupBoxSimulText)
        self.textSimulDir.setReadOnly(False)
        self.textSimulDir.setObjectName("textSimulDir")
        self.horizontalLayout2.addWidget(self.textSimulDir)
        self.buttonBrowseSimulDir = QtWidgets.QPushButton(self.groupBoxSimulText)
        self.buttonBrowseSimulDir.setObjectName("buttonBrowseSimulDir")
        self.horizontalLayout2.addWidget(self.buttonBrowseSimulDir)
        self.gridLayout_2.addLayout(self.horizontalLayout2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBoxSimulText)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxSimulText, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 158, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonCancel = QtWidgets.QPushButton(QGridderSettings)
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout_2.addWidget(self.buttonCancel)
        self.buttonOK = QtWidgets.QPushButton(QGridderSettings)
        self.buttonOK.setObjectName("buttonOK")
        self.horizontalLayout_2.addWidget(self.buttonOK)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(QGridderSettings)
        QtCore.QMetaObject.connectSlotsByName(QGridderSettings)

    def retranslateUi(self, QGridderSettings):
        _translate = QtCore.QCoreApplication.translate
        QGridderSettings.setWindowTitle(_translate("QGridderSettings", "Qgridder Settings"))
        self.groupBox_4.setTitle(_translate("QGridderSettings", "Grid refinement"))
        self.label_22.setText(_translate("QGridderSettings", "Model type :"))
        self.checkGridBackup.setText(_translate("QGridderSettings", "Backup grids when refining "))
        self.groupBox.setTitle(_translate("QGridderSettings", "Plotting"))
        self.checkPlotSimul.setText(_translate("QGridderSettings", "Plot simulated  values"))
        self.textObsDir.setText(_translate("QGridderSettings", "obs_dir"))
        self.buttonBrowseObsDir.setText(_translate("QGridderSettings", "Browse..."))
        self.checkPlotObs.setText(_translate("QGridderSettings", "Plot observed values"))
        self.labelSimulSources.setText(_translate("QGridderSettings", "Source of simulation data: "))
        self.groupBoxSimulFlopy.setTitle(_translate("QGridderSettings", "Simulated data from Flopy model"))
        self.labe.setText(_translate("QGridderSettings", "Path to model python module :"))
        self.textModelDir.setText(_translate("QGridderSettings", "model_src_dir"))
        self.buttonBrowseModelSrcDir.setText(_translate("QGridderSettings", "Browse..."))
        self.labe_3.setText(_translate("QGridderSettings", "Simulation file :"))
        self.textSimulFile.setText(_translate("QGridderSettings", "simul_file"))
        self.buttonBrowseSimulFile.setText(_translate("QGridderSettings", "Browse..."))
        self.label_2.setText(_translate("QGridderSettings", "Simulation start date (format %Y-%m-%d %H:%M) :"))
        self.textSimulStartDate.setText(_translate("QGridderSettings", "2015-01-01 00:00"))
        self.labelGridLayer.setText(_translate("QGridderSettings", "Grid layer :"))
        self.labe_2.setText(_translate("QGridderSettings", "Path to CSV observation files :"))
        self.groupBoxSimulText.setTitle(_translate("QGridderSettings", "Simulated data from text "))
        self.textSimulDir.setText(_translate("QGridderSettings", "simul_dir"))
        self.buttonBrowseSimulDir.setText(_translate("QGridderSettings", "Browse..."))
        self.label_3.setText(_translate("QGridderSettings", "Path to CSV simulation files:"))
        self.buttonCancel.setText(_translate("QGridderSettings", "Cancel"))
        self.buttonOK.setText(_translate("QGridderSettings", "OK"))

