# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qgridder_refinement.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QGridderRefinement(object):
    def setupUi(self, QGridderRefinement):
        QGridderRefinement.setObjectName("QGridderRefinement")
        QGridderRefinement.resize(548, 233)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(QGridderRefinement)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelGridLayer = QtWidgets.QLabel(QGridderRefinement)
        self.labelGridLayer.setObjectName("labelGridLayer")
        self.horizontalLayout_11.addWidget(self.labelGridLayer)
        self.listGridLayer = QtWidgets.QComboBox(QGridderRefinement)
        self.listGridLayer.setEnabled(True)
        self.listGridLayer.setObjectName("listGridLayer")
        self.horizontalLayout_11.addWidget(self.listGridLayer)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.label_9 = QtWidgets.QLabel(QGridderRefinement)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(QGridderRefinement)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.sboxDivideHoriz = QtWidgets.QSpinBox(QGridderRefinement)
        self.sboxDivideHoriz.setMinimum(1)
        self.sboxDivideHoriz.setMaximum(100)
        self.sboxDivideHoriz.setProperty("value", 2)
        self.sboxDivideHoriz.setObjectName("sboxDivideHoriz")
        self.horizontalLayout.addWidget(self.sboxDivideHoriz)
        self.label_10 = QtWidgets.QLabel(QGridderRefinement)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.sboxDivideVert = QtWidgets.QSpinBox(QGridderRefinement)
        self.sboxDivideVert.setMinimum(1)
        self.sboxDivideVert.setMaximum(100)
        self.sboxDivideVert.setProperty("value", 2)
        self.sboxDivideVert.setObjectName("sboxDivideVert")
        self.horizontalLayout.addWidget(self.sboxDivideVert)
        self.checkDivideRatio = QtWidgets.QCheckBox(QGridderRefinement)
        self.checkDivideRatio.setChecked(True)
        self.checkDivideRatio.setObjectName("checkDivideRatio")
        self.horizontalLayout.addWidget(self.checkDivideRatio)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkTopo = QtWidgets.QCheckBox(QGridderRefinement)
        self.checkTopo.setChecked(True)
        self.checkTopo.setObjectName("checkTopo")
        self.horizontalLayout_8.addWidget(self.checkTopo)
        spacerItem = QtWidgets.QSpacerItem(128, 21, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBarRegularRefine = QtWidgets.QProgressBar(QGridderRefinement)
        self.progressBarRegularRefine.setProperty("value", 0)
        self.progressBarRegularRefine.setObjectName("progressBarRegularRefine")
        self.horizontalLayout_2.addWidget(self.progressBarRegularRefine)
        self.labelIterations = QtWidgets.QLabel(QGridderRefinement)
        self.labelIterations.setObjectName("labelIterations")
        self.horizontalLayout_2.addWidget(self.labelIterations)
        self.labelIter = QtWidgets.QLabel(QGridderRefinement)
        self.labelIter.setObjectName("labelIter")
        self.horizontalLayout_2.addWidget(self.labelIter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonUndoRefine = QtWidgets.QPushButton(QGridderRefinement)
        self.buttonUndoRefine.setEnabled(False)
        self.buttonUndoRefine.setObjectName("buttonUndoRefine")
        self.horizontalLayout_2.addWidget(self.buttonUndoRefine)
        self.buttonRefine = QtWidgets.QPushButton(QGridderRefinement)
        self.buttonRefine.setObjectName("buttonRefine")
        self.horizontalLayout_2.addWidget(self.buttonRefine)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)

        self.retranslateUi(QGridderRefinement)
        QtCore.QMetaObject.connectSlotsByName(QGridderRefinement)

    def retranslateUi(self, QGridderRefinement):
        _translate = QtCore.QCoreApplication.translate
        QGridderRefinement.setWindowTitle(_translate("QGridderRefinement", "Qgridder Refinement"))
        self.labelGridLayer.setText(_translate("QGridderRefinement", "Grid layer :"))
        self.label_9.setText(_translate("QGridderRefinement", "Divide by :"))
        self.label_11.setText(_translate("QGridderRefinement", "horizontally :"))
        self.label_10.setText(_translate("QGridderRefinement", "vertically :"))
        self.checkDivideRatio.setText(_translate("QGridderRefinement", "Lock 1:1 ratio"))
        self.checkTopo.setText(_translate("QGridderRefinement", "Check topology  for selected model type"))
        self.labelIterations.setText(_translate("QGridderRefinement", "Iterations : "))
        self.labelIter.setText(_translate("QGridderRefinement", "0"))
        self.buttonUndoRefine.setText(_translate("QGridderRefinement", "Undo"))
        self.buttonRefine.setText(_translate("QGridderRefinement", "Refine selection "))

