# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qgridder_new.ui'
#
# Created: Fri May 15 11:15:19 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QGridderNew(object):
    def setupUi(self, QGridderNew):
        QGridderNew.setObjectName(_fromUtf8("QGridderNew"))
        QGridderNew.resize(546, 511)
        self.verticalLayout_7 = QtGui.QVBoxLayout(QGridderNew)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox = QtGui.QGroupBox(QGridderNew)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.buttonUpdateFromLayer = QtGui.QPushButton(self.groupBox)
        self.buttonUpdateFromLayer.setObjectName(_fromUtf8("buttonUpdateFromLayer"))
        self.gridLayout_3.addWidget(self.buttonUpdateFromLayer, 0, 0, 1, 1)
        self.buttonUpdateFromCanvas = QtGui.QPushButton(self.groupBox)
        self.buttonUpdateFromCanvas.setObjectName(_fromUtf8("buttonUpdateFromCanvas"))
        self.gridLayout_3.addWidget(self.buttonUpdateFromCanvas, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.listSourceLayer = QtGui.QComboBox(self.groupBox)
        self.listSourceLayer.setObjectName(_fromUtf8("listSourceLayer"))
        self.gridLayout_4.addWidget(self.listSourceLayer, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.textXmin = QtGui.QLineEdit(self.groupBox)
        self.textXmin.setObjectName(_fromUtf8("textXmin"))
        self.gridLayout_2.addWidget(self.textXmin, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.textYmin = QtGui.QLineEdit(self.groupBox)
        self.textYmin.setObjectName(_fromUtf8("textYmin"))
        self.gridLayout_2.addWidget(self.textYmin, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.textYmax = QtGui.QLineEdit(self.groupBox)
        self.textYmax.setObjectName(_fromUtf8("textYmax"))
        self.gridLayout_2.addWidget(self.textYmax, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_1 = QtGui.QLabel(self.groupBox)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout_2.addWidget(self.label_1, 1, 0, 1, 1)
        self.textXmax = QtGui.QLineEdit(self.groupBox)
        self.textXmax.setObjectName(_fromUtf8("textXmax"))
        self.gridLayout_2.addWidget(self.textXmax, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 4, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(QGridderNew)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sboxYres = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.sboxYres.setEnabled(True)
        self.sboxYres.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxYres.setMaximum(1000000000.0)
        self.sboxYres.setObjectName(_fromUtf8("sboxYres"))
        self.gridLayout_5.addWidget(self.sboxYres, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 1)
        self.sboxXres = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.sboxXres.setMinimumSize(QtCore.QSize(150, 0))
        self.sboxXres.setMaximum(1000000000.0)
        self.sboxXres.setObjectName(_fromUtf8("sboxXres"))
        self.gridLayout_5.addWidget(self.sboxXres, 0, 2, 1, 1)
        self.checkRatio = QtGui.QCheckBox(self.groupBox_2)
        self.checkRatio.setObjectName(_fromUtf8("checkRatio"))
        self.gridLayout_5.addWidget(self.checkRatio, 0, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.labelNumberCells = QtGui.QLabel(self.groupBox_2)
        self.labelNumberCells.setText(_fromUtf8(""))
        self.labelNumberCells.setObjectName(_fromUtf8("labelNumberCells"))
        self.horizontalLayout_9.addWidget(self.labelNumberCells)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(QGridderNew)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.checkLoadLayer = QtGui.QCheckBox(self.groupBox_3)
        self.checkLoadLayer.setObjectName(_fromUtf8("checkLoadLayer"))
        self.gridLayout_8.addWidget(self.checkLoadLayer, 2, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.textOutFilename = QtGui.QLineEdit(self.groupBox_3)
        self.textOutFilename.setObjectName(_fromUtf8("textOutFilename"))
        self.gridLayout_7.addWidget(self.textOutFilename, 3, 1, 1, 1)
        self.buttonBrowse = QtGui.QPushButton(self.groupBox_3)
        self.buttonBrowse.setObjectName(_fromUtf8("buttonBrowse"))
        self.gridLayout_7.addWidget(self.buttonBrowse, 3, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 3, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.progressBarBuildGrid = QtGui.QProgressBar(QGridderNew)
        self.progressBarBuildGrid.setProperty("value", 0)
        self.progressBarBuildGrid.setObjectName(_fromUtf8("progressBarBuildGrid"))
        self.horizontalLayout_3.addWidget(self.progressBarBuildGrid)
        self.labelIter = QtGui.QLabel(QGridderNew)
        self.labelIter.setObjectName(_fromUtf8("labelIter"))
        self.horizontalLayout_3.addWidget(self.labelIter)
        spacerItem = QtGui.QSpacerItem(78, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonWriteGrid = QtGui.QPushButton(QGridderNew)
        self.buttonWriteGrid.setObjectName(_fromUtf8("buttonWriteGrid"))
        self.horizontalLayout_3.addWidget(self.buttonWriteGrid)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)

        self.retranslateUi(QGridderNew)
        QtCore.QMetaObject.connectSlotsByName(QGridderNew)
        QGridderNew.setTabOrder(self.listSourceLayer, self.buttonUpdateFromLayer)
        QGridderNew.setTabOrder(self.buttonUpdateFromLayer, self.buttonUpdateFromCanvas)
        QGridderNew.setTabOrder(self.buttonUpdateFromCanvas, self.textXmin)
        QGridderNew.setTabOrder(self.textXmin, self.textYmin)
        QGridderNew.setTabOrder(self.textYmin, self.textXmax)
        QGridderNew.setTabOrder(self.textXmax, self.textYmax)
        QGridderNew.setTabOrder(self.textYmax, self.sboxXres)
        QGridderNew.setTabOrder(self.sboxXres, self.sboxYres)
        QGridderNew.setTabOrder(self.sboxYres, self.checkRatio)
        QGridderNew.setTabOrder(self.checkRatio, self.textOutFilename)
        QGridderNew.setTabOrder(self.textOutFilename, self.buttonBrowse)
        QGridderNew.setTabOrder(self.buttonBrowse, self.checkLoadLayer)
        QGridderNew.setTabOrder(self.checkLoadLayer, self.buttonWriteGrid)

    def retranslateUi(self, QGridderNew):
        QGridderNew.setWindowTitle(_translate("QGridderNew", "Qgridder", None))
        self.groupBox.setTitle(_translate("QGridderNew", "Grid extent", None))
        self.buttonUpdateFromLayer.setText(_translate("QGridderNew", "Update extents from layer", None))
        self.buttonUpdateFromCanvas.setText(_translate("QGridderNew", "Update extents from canvas", None))
        self.textXmin.setText(_translate("QGridderNew", "0", None))
        self.label_2.setText(_translate("QGridderNew", "Y Min", None))
        self.textYmin.setText(_translate("QGridderNew", "0", None))
        self.label_3.setText(_translate("QGridderNew", "X Min", None))
        self.textYmax.setText(_translate("QGridderNew", "100", None))
        self.label_4.setText(_translate("QGridderNew", "Y Max", None))
        self.label_1.setText(_translate("QGridderNew", "X Max", None))
        self.textXmax.setText(_translate("QGridderNew", "100", None))
        self.label_7.setText(_translate("QGridderNew", "Fectch extents from existing layer : ", None))
        self.label_8.setText(_translate("QGridderNew", "Note : maximum values of X and Y will be adjusted to obtain exact resolution.", None))
        self.groupBox_2.setTitle(_translate("QGridderNew", "Grid resolution (in map unit)", None))
        self.label_6.setText(_translate("QGridderNew", "Y", None))
        self.label_5.setText(_translate("QGridderNew", "X", None))
        self.checkRatio.setText(_translate("QGridderNew", " 1:1 ratio", None))
        self.label_13.setText(_translate("QGridderNew", "Estimated number of grid cells : ", None))
        self.groupBox_3.setTitle(_translate("QGridderNew", "Output", None))
        self.checkLoadLayer.setText(_translate("QGridderNew", "Load layer after creation", None))
        self.textOutFilename.setText(_translate("QGridderNew", "grid.shp", None))
        self.buttonBrowse.setText(_translate("QGridderNew", "Browse...", None))
        self.label.setText(_translate("QGridderNew", "Output layer", None))
        self.labelIter.setText(_translate("QGridderNew", "labelIter", None))
        self.buttonWriteGrid.setText(_translate("QGridderNew", "Build grid", None))

